# Generated by Django 4.1.7 on 2023-04-05 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_mensagem_destinatario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensagem",
            name="sala",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mensagens",
                to="core.sala",
            ),
        ),
    ]
